name: Build and Publish Container

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Log in to GitHub Container Registry
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Build the container image with versioning
            - name: Build container image
              run: |
                  IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
                  GIT_SHA=${{ github.sha }}
                  docker build -t $IMAGE_TAG:latest -t $IMAGE_TAG:$GIT_SHA .

            # Push the container image to GitHub Container Registry
            - name: Push container image
              run: |
                  IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
                  GIT_SHA=${{ github.sha }}
                  docker push $IMAGE_TAG:latest
                  docker push $IMAGE_TAG:$GIT_SHA
